# Generated by Django 5.0 on 2023-12-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commmerce', '0002_cart_is_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_attempt_count',
            field=models.IntegerField(default=0),
        ),
    ]
